crc10do9.exe: crc10do9.obj
	g++ crc10do9.obj -o crc10do9.exe


crc10do9.obj: crc10do9.asm
	nasm -f win64 crc10do9.asm -o crc10do9.obj
	

crc10do6.exe: crc10do6.obj
	g++ crc10do6.obj -o crc10do6.exe


crc10do6.obj: crc10do6.asm
	nasm -f win64 crc10do6.asm -o crc10do6.obj	


crc10do10.exe: crc10do10.obj
	g++ crc10do10.obj -o crc10do10.exe


crc10do10.obj: crc10do10.asm
	nasm -f win64 crc10do10.asm -o crc10do10.obj


crc10do12.exe: crc10do12.obj
	g++ crc10do12.obj -o crc10do12.exe


crc10do12.obj: crc10do12.asm
	nasm -f win64 crc10do12.asm -o crc10do12.obj